name: Deploy Web

on:
  push:
    branches: [main]
    paths:
      - web/**

jobs:
  cd-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Predeploy
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
